---
Description: "Nginx, Application LoadBalancer,Target Group, ASG and Launch Template. Used for testing
              tenant-vpc architectures and intended to be deployed as an internal load-balanced test 
              application. Deploy this as the proxy target to the nginxAlbv2ReverseProxyCluster or 
              nginxNLBv2Cluster stacks"
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  App:
    Type: String
    AllowedValues:
      - api
      - www
    Description: "Select endpoint proxy (api|www)"
  ASI:
    Type: String
    MinLength: 2
    MaxLength: 5
    Description: "asi - must be lower-case, limit 4 characters"
    AllowedPattern: "[a-z]*"
  Environment:
    Type: String
    MinLength: 3
    MaxLength: 7
    Description: "environment (nonprod|dev|itg|cat|prod) - must be lower-case, limit 7 characters"
    AllowedPattern: "[a-z]*"
  Owner:
    Type: String
    Description: "email address of the the Owner of this stack"
    Default: "admin@root.com"
    AllowedPattern: "^[\\w-\\+]+(\\.[\\w]+)*@[\\w-]+(\\.[\\w]+)*(\\.[a-z]{2,})$"
  ConfigVersion:
    Type: String
    Description: "major.minor version of the config to use, eg: 1.0"
    MinLength: 3
    MaxLength: 5
    AllowedPattern: '(\d{1,2})\.(\d{1,2})'
  DeploymentBucketName:
    Type: String
    Description: "s3 bucket where deployment files are kept"
  certificatearn:
    Type: String
    Description: "arn for the load balancer tls listener certificate"
  vpcid:
    Type: AWS::EC2::VPC::Id
  keyname:
    Type: AWS::EC2::KeyPair::KeyName
  subnetid:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "private subnets for autoscale group"
  EnvironmentSize:
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE
Mappings:
  RegionMap:
    us-east-1:
      "AMALINUX2" : "ami-035be7bafff33b6b6"
    us-west-2:
      "AMALINUX2" : "ami-032509850cf9ee54e"
  InstanceSize:
    SMALL:
      "EC2" : "t3.small"
    MEDIUM:
      "EC2" : "t3.medium"
    LARGE:
      "EC2" : "t3.large"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - 
      Label:
        default: "Environment Configuration"
      Parameters:
        - App
        - ASI
        - Environment
        - Owner
        - ConfigVersion
    -
      Label: 
        default: "Network Configuration"
      Parameters:
        - vpcid
        - subnetid
    -
      Label:
        default: "Launch Template Configuration"
      Parameters:
        - DeploymentBucketName
        - EnvironmentSize
        - keyname
        - certificatearn

Resources:
  LaunchTemplate: 
    Type: "AWS::EC2::LaunchTemplate"
    Metadata:
      AWS::CloudFormation::Authentication:
        S3Access:
          type: "S3"
          buckets:
            - !Ref DeploymentBucketName
          roleName:
            Ref: NgxLtRole
      AWS::CloudFormation::Init:
        configSets:
          nginx:
            - "configure_cfn"
            - "config_certificates"
            - "config_nginx"
            - "install_awslogs"
            - "verify_instance_health"
        configure_cfn:
          files:
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.LaunchTemplate.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource LaunchTemplate --configsets nginx --region ${AWS::Region}
              mode: "000400"
              owner: root
              group: root
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
                verbose=true
                interval=5
              mode: "000400"
              owner: root
              group: root
          services:
            sysvinit:
              cfn-hup:
                enabled: true
                ensureRunning: true
                files:
                  - "/etc/cfn/cfn-hup.conf"
                  - "/etc/cfn/hooks.d/cfn-auto-reloader.conf"
        config_certificates:
          commands:
            01_mkdir:
              command: mkdir -m 700 /etc/ssl/private
            02_mkcert:
              command: !Sub |
                openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
                -keyout /etc/ssl/private/nginx-selfsigned.key \
                -out /etc/ssl/certs/nginx-selfsigned.crt \
                -subj '/C=US/ST=Nebraska/L=Omaha/O=${ASI}/OU=${Environment}/CN=${App}.${Environment}.${ASI}.aws.service/emailAddress=${Owner}'
        config_nginx:
          commands:
            01_install_nginx:
              command: amazon-linux-extras install nginx1.12 -y
            02_enable_nginx:
              command: /bin/systemctl enable nginx.service
            03_start_nginx:
              command: /bin/systemctl restart nginx.service
          files:
            /var/www/html/index.html:
              content: !Sub |
                <html>
                  <body>
                    Hello from ${App}.${Environment}.${ASI}.aws.service
                  </body>
                </html>
              mode: "000644"
              owner: root
              group: root
            /etc/nginx/nginx.conf:
              content: !Sub |
                user nginx;
                worker_processes auto;
                error_log /var/log/nginx/error.log;
                events {
                  worker_connections 1024;
                }
                http {
                  log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                                    '$status $body_bytes_sent "$http_referer" '
                                    '"$http_user_agent" "$http_x_forwarded_for"';

                  access_log /var/log/nginx/access.log  main;
                  sendfile on;
                  tcp_nopush          on;
                  tcp_nodelay         on;
                  keepalive_timeout   65;
                  types_hash_max_size 2048;
 
                  include             /etc/nginx/mime.types;
                  default_type        application/octet-stream;

                  server {
                    listen       443 ssl http2 default_server;
                    server_name  ${App}.${Environment}.${ASI}.aws.service;
                    root         /usr/share/nginx/html;
                    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
                    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
                    ssl_session_cache shared:SSL:1m;
                    ssl_session_timeout  10m;
                    ssl_ciphers HIGH:!aNULL:!MD5;
                    ssl_prefer_server_ciphers on;

                    location / {
                      root /var/www/html;
                    }
                    location /health {
                      default_type  application/json;
                      return 200 '{"message": "healthy"}';
                    }

                    location ^~ /internal/ {
                      return 404;
                    }

                    error_page 404 /404.html;
                      location = /404.html {
                    }

                    error_page 500 502 503 504 /50x.html;
                      location = /50x.html {
                    }
                  }
                }
              mode: 000644
              owner: root
              group: root
              # cfn-init supports sysvinit, not systemd, so no services here. See above.
        install_awslogs:
          commands:
            01_install_awslogs:
              command: yum install -y awslogs
            02_configure_awslogs:
              command: cp /tmp/awslogs/awscli.conf /etc/awslogs/awscli.conf
          files:
            /etc/awslogs/awslogs.conf:
              content: !Sub |
                [general]
                state_file = /var/lib/awslogs/agent-state
                use_gzip_http_content_encoding = true

                [nginx]
                file = /var/log/nginx/access.log
                log_group_name = ${ASI}-${Environment}-${App}-proxy-log-group
                log_stream_name = ${ASI}-${Environment}-${App}-access-logs
                datetime_format = %b %d %H:%M:%S
                buffer_duration = 5000
                initial_position = start_of_file
            /tmp/awslogs/awscli.conf:
              content: !Sub |
                [plugins]
                cwlogs = cwlogs
                [default]
                region = ${AWS::Region}
          services:
            sysvinit:
              awslogsd:
                enabled: "true"
                ensureRunning: "true"
                files:
                  - "/etc/awslogs/awslogs.conf"
                  - "/etc/awslogs/awscli.conf"
        verify_instance_health:
          commands:
            ELBV2HealthCheck:
              command: !Sub
                'until [ "$state" == "\"healthy\"" ]; do state=$(aws --region ${AWS::Region} elbv2 describe-target-health
                --target-group-arn ${TargetGroup443}
                --targets Id=$(curl -ks http://169.254.169.254/latest/meta-data/instance-id),Port=443
                --query TargetHealthDescriptions[0].TargetHealth.State); sleep 10; done'

    Properties:
      LaunchTemplateName: !Join ["-", [!Ref "AWS::StackName", "nginx", !Ref App]]
      LaunchTemplateData:
        IamInstanceProfile: 
            Name: !Join ["-", [!Ref "AWS::StackName", !Ref "AWS::Region", "Ec2Profile"]]
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMALINUX2]
        InstanceType: !FindInMap [InstanceSize, !Ref EnvironmentSize, EC2]
        KeyName: !Ref keyname
        SecurityGroupIds:
          - !Ref AutoScaleGroupSg
        UserData:
          "Fn::Base64":
            !Sub |
              #!/usr/bin/env bash
              # configVersion ${ConfigVersion}
              yum update -y # good practice - always do this.
              /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource LaunchTemplate --configsets nginx --region ${AWS::Region}
              /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource AutoScalingGroup --region ${AWS::Region}

# Begin other resource definitions
  AutoScaleGroupSg:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: !Ref "AWS::StackName"
      GroupDescription: "nginx security group"
      VpcId: !Ref vpcid
      SecurityGroupIngress:
        -
          CidrIp: 10.0.0.0/8
          IpProtocol: "-1"
          ToPort: -1
          FromPort: -1
        -
          CidrIp: 10.0.0.0/8
          IpProtocol: "TCP"
          ToPort: 80
          FromPort: 80
        -
          CidrIp: 10.0.0.0/8
          IpProtocol: "TCP"
          ToPort: 443
          FromPort: 443
      SecurityGroupEgress:
        -
          CidrIp: 0.0.0.0/0
          ToPort: -1
          IpProtocol: "-1"
      Tags:
        -
          Key: "Name"
          Value: !Sub "${App}-${Environment}-${ASI}-asg-sg"
        -
          Key: "Project"
          Value: !Ref ASI
        -
          Key: "Environment"
          Value: !Ref Environment
        -
          Key: "Owner"
          Value: !Ref Owner

  AutoScalingGroup:
    DependsOn: RootInstanceProfile
    Type: "AWS::AutoScaling::AutoScalingGroup"
    CreationPolicy:
      ResourceSignal:
       Count: "1"
       Timeout: PT15M        
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MaxBatchSize: 1
        MinInstancesInService: 1
        PauseTime: PT15M
        WaitOnResourceSignals: true
    Properties:
      MinSize: "2"
      MaxSize: "5"
      Cooldown: "120"
      DesiredCapacity: "2"
      LaunchTemplate:
        LaunchTemplateId:
          Ref: "LaunchTemplate"
        Version:
          Fn::GetAtt:
            [ "LaunchTemplate", "LatestVersionNumber" ]
      VPCZoneIdentifier: !Ref subnetid
      TargetGroupARNs: 
        - !Ref TargetGroup443
      Tags:
      - 
        Key: "Name"
        Value: !Sub "${App}-${Environment}-${ASI}-alb-asg"
        PropagateAtLaunch: true      
      -
        Key: "Project"
        Value: !Ref ASI
        PropagateAtLaunch: true      
      -
        Key: "Environment"
        Value: !Ref Environment
        PropagateAtLaunch: true      
      -
        Key: "Owner"
        Value: !Ref Owner
        PropagateAtLaunch: true      

  TargetGroup443:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 443
      Protocol: "HTTPS"
      VpcId: !Ref vpcid
      HealthCheckProtocol: "HTTPS"
      HealthCheckPort: "443"
      HealthCheckIntervalSeconds: 30
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      Tags:
      - 
        Key: "Name"
        Value: !Sub "${App}-${Environment}-${ASI}-nginx-tg"
      -
        Key: "Project"
        Value: !Ref ASI
      -
        Key: "Environment"
        Value: !Ref Environment
      -
        Key: "Owner"
        Value: !Ref Owner

  ElasticLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: "internal"
      Subnets: !Ref subnetid
      Tags:
        - 
          Key: "Name"
          Value: !Sub "${App}-${Environment}-${ASI}-https-alb"
        -
          Key: "Project"
          Value: !Ref ASI
        -
          Key: "Environment"
          Value: !Ref Environment
        -
          Key: "Owner"
          Value: !Ref Owner
      Type: "application"

  LoadBalancer443:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn: !Ref certificatearn
      LoadBalancerArn: !Ref ElasticLoadBalancer
      Port: 443
      Protocol: HTTPS
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup443
      SslPolicy: "ELBSecurityPolicy-2016-08"

  NgxLtRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
  RolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: nginxEC2
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - ssm:DescribeAssociation
          - ssm:GetDeployablePatchSnapshotForInstance
          - ssm:GetDocument
          - ssm:DescribeDocument
          - ssm:GetManifest
          - ssm:GetParameters
          - ssm:ListAssociations
          - ssm:ListInstanceAssociations
          - ssm:PutInventory
          - ssm:PutComplianceItems
          - ssm:PutConfigurePackageResult
          - ssm:UpdateAssociationStatus
          - ssm:UpdateInstanceAssociationStatus
          - ssm:UpdateInstanceInformation
          Resource: "*"
        - Effect: Allow
          Action:
          - ssmmessages:CreateControlChannel
          - ssmmessages:CreateDataChannel
          - ssmmessages:OpenControlChannel
          - ssmmessages:OpenDataChannel
          Resource: "*"
        - Effect: Allow
          Action:
          - ec2messages:AcknowledgeMessage
          - ec2messages:DeleteMessage
          - ec2messages:FailMessage
          - ec2messages:GetEndpoint
          - ec2messages:GetMessages
          - ec2messages:SendReply
          Resource: "*"
        - Effect: Allow
          Action:
          - cloudwatch:PutMetricData
          Resource: "*"
        - Effect: Allow
          Action:
          - ec2:DescribeInstanceStatus
          Resource: "*"
        - Effect: Allow
          Action:
          - elasticloadbalancing:DescribeTargetHealth
          Resource: "*"
        - Effect: Allow
          Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:DescribeLogGroups
          - logs:DescribeLogStreams
          - logs:PutLogEvents         
          Resource: "*"
        - Effect: Allow
          Action: 
          - s3:GetBucketLocation
          - s3:GetObject
          - s3:GetEncryptionConfiguration
          - s3:AbortMultipartUpload
          - s3:ListMultipartUploadParts
          - s3:ListBucket
          - s3:ListBucketMultipartUploads
          Resource: 
            - !Sub 'arn:aws:s3:::${DeploymentBucketName}'
            - !Sub 'arn:aws:s3:::${DeploymentBucketName}/*'
      Roles:
      - !Ref NgxLtRole
  RootInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref NgxLtRole
      InstanceProfileName: !Join ["-", [!Ref "AWS::StackName", !Ref "AWS::Region", "Ec2Profile"]]
Outputs:
  proxyPassEndpoint:
    Description: 'Internal Url'
    Value: !Join ["", ["https://", !GetAtt ElasticLoadBalancer.DNSName]]
  configVersion:
    Description: "ConfigVersion -- useful for rolling an update"
    Value: !Ref ConfigVersion
# ToDo: may need to validate message content headers
