---
Description: "Nginx proxy Network LoadBalancer,Target Group, ASG and Launch Template"
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  vpcid:
    Type: AWS::EC2::VPC::Id
  keyname:
    Type: AWS::EC2::KeyPair::KeyName
  securitygroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: "EC2 Security group for instance"
  publicsubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "public subnets for nlb"
  subnetid:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "need subnet id for EC2 instance"
Mappings:
  RegionMap:
    us-east-1:
      "AMALINUX2" : "ami-035be7bafff33b6b6"
    us-west-2:
      "AMALINUX2" : "ami-032509850cf9ee54e"

Resources:
  LaunchTemplate: 
    Type: "AWS::EC2::LaunchTemplate"
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          nginx:
            - "configure_cfn"
            - "config_nginx"
            - "verify_instance_health"
        configure_cfn:
          files:
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.LaunchTemplate.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource LaunchTemplate --configsets nginx --region ${AWS::Region}
              mode: "000400"
              owner: root
              group: root
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
                verbose=true
                interval=5
              mode: "000400"
              owner: root
              group: root
          services:
            sysvinit:
              cfn-hup:
                enabled: true
                ensureRunning: true
                files:
                  - "/etc/cfn/cfn-hup.conf"
                  - "/etc/cfn/hooks.d/cfn-auto-reloader.conf"
        config_nginx:
          sources: 
            /etc/nginx: "https://github.com/fortunecookiezen/ec2nginx/tarball/master"
          services: 
            sysvinit: 
              nginx: 
                enabled: true
                ensureRunning: true
                files: 
                  - "/etc/nginx/nginx.conf"
        verify_instance_health:
          commands:
            ELBHealthCheck:
              command: !Sub
                'until [ "$state" == "\"InService\"" ]; do state=$(aws --region ${AWS::Region} elb describe-instance-health
                 --load-balancer-name ${ElasticLoadBalancer}
                 --instances $(curl -s http://169.254.169.254/latest/meta-data/instance-id)
                 --query InstanceStates[0].State); sleep 10; done'
    Properties:
      LaunchTemplateName: "nginx"
      LaunchTemplateData:
        IamInstanceProfile: 
            Name: "Ec2SsmRole"
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMALINUX2]
        InstanceType: "t3.small"
        KeyName: !Ref keyname
        SecurityGroupIds:
          - !Ref securitygroup
        UserData:
          "Fn::Base64":
            !Sub |
              #!/usr/bin/env bash
              yum update -y aws-cfn-bootstrap # good practice - always do this.
              /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource LaunchTemplate --configsets nginx --region ${AWS::Region}
              yum -y update
              amazon-linux-extras install nginx1.12 -y
              /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource AutoScalingGroup --region ${AWS::Region}
              /bin/systemctl enable nginx.service #manually enable this thing
              /bin/systemctl restart nginx.service #manually kick this thing

# Begin other resource definitions
  AutoScalingGroup:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    CreationPolicy:
      ResourceSignal:
       Count: "1"
       Timeout: PT15M        
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MaxBatchSize: 1
        MinInstancesInService: 1
        PauseTime: PT15M
        WaitOnResourceSignals: true
    Properties:
#      AvailabilityZones: !GetAZs ""
      MinSize: "2"
      MaxSize: "5"
      Cooldown: "120"
      DesiredCapacity: "2"
      LaunchTemplate:
        LaunchTemplateId:
          Ref: "LaunchTemplate"
        Version:
          Fn::GetAtt:
            [ "LaunchTemplate", "LatestVersionNumber" ]
      VPCZoneIdentifier: !Ref subnetid
        #- ""
        #- ""
      TargetGroupARNs: 
        - !Ref TargetGroup
      Tags:
      - Key: "Name"
        Value: "nlb-asg"
        PropagateAtLaunch: true      

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: "TCP"
      VpcId: !Ref vpcid
      HealthCheckProtocol: "HTTP"
      HealthCheckPort: "80"
      HealthCheckIntervalSeconds: 30
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      Tags:
      - Key: "Name"
        Value: "nginx-tg"

  ElasticLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets: !Ref publicsubnets
      Scheme: "internet-facing"
#      SubnetMappings:
#        - AllocationId: !Ref firsteipallocationid
#          SubnetId: !Ref lbsubneta
#        - AllocationId: !Ref secondeipallocationid
#          SubnetId: !Ref lbsubnetb
      Tags:
        - Key: "Name"
          Value: "http-nlb"
      Type: "network"

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ElasticLoadBalancer
      Port: 80
      Protocol: TCP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup


# to do: add proper security groups to this
# restrict launch template to elb
# create security groups for launch template and allow nlb traffic through (80/443)
# add logging, health checks, and notifications
# add creation of IAM role for this group to the file: enable S3 access for configs, etc.      